# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release

on: workflow_dispatch
env: 
 KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
 KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
 KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous workflow runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
          
      - name: Decode Keystore file
        run: echo $ENCODED_KEYSTORE | base64 -di > "${HOME}"/keystore.jks
        env:
          ENCODED_KEYSTORE: ${{ secrets.KEYSTORE_FILE }}  

      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  

      - name: Generate AAB (Android App Bundle) file
        run: ./gradlew :sample:bundleRelease -x :sample:testReleaseUnitTest --stacktrace
        
      - name: Upload AAB file to tag assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sample/build/outputs/bundle/release/sample-release.aab
          asset_name: "sample-$tag.aab"
          tag: ${{ github.ref }}
          overwrite: true      
      
      - name: Generate APK (Android App PacKage) file
        run: ./gradlew :sample:assembleRelease -x :sample:testReleaseUnitTest --stacktrace
        
      - name: Upload APK file to tag assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: sample/build/outputs/apk/release/sample-release.apk
          asset_name: "sample-$tag.apk"
          tag: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') }}
          overwrite: true
